---
base:
  data_dir: {data-dir}
  role: validator
  waypoint:
    from_config: "0:f7f746b64ed9c77be826a076913a2f298b51b7923083f2c67e965d3d791e7f98"
consensus:
  max_block_txns: 6000
  max_block_bytes: 5242880
  max_pruned_blocks_in_mem: 100
  mempool_executed_txn_timeout_ms: 1000
  mempool_txn_pull_timeout_ms: 1000
  round_initial_timeout_ms: 1500
  round_timeout_backoff_exponent_base: 1.2
  round_timeout_backoff_max_exponent: 6
  safety_rules:
    backend:
      type: rocks_db_storage
      path: secure_storage_db
      namespace: ~
    logger:
      chan_size: 10000
      enable_backtrace: false
      is_async: true
      level: INFO
      console_port: ~
      enable_telemetry_remote_log: true
      enable_telemetry_flush: true
      telemetry_level: ERROR
    service:
      type: thread
    test: ~
    network_timeout_ms: 30000
    enable_cached_safety_data: true
    initial_safety_rules_config:
      from_file:
        identity_blob_path: {validator-identity-file}
        waypoint:
          from_config: "0:f7f746b64ed9c77be826a076913a2f298b51b7923083f2c67e965d3d791e7f98"
  sync_only: false
  channel_size: 30
  use_quorum_store: false
  quorum_store_pull_timeout_ms: 1000
  quorum_store_poll_count: 5
  intra_consensus_channel_buffer_size: 10
execution:
  genesis_file_location: {genesis-file}
  concurrency_level: 8
  num_proof_reading_threads: 32
full_node_networks:
  - max_connection_delay_ms: 60000
    connection_backoff_base: 2
    connectivity_check_interval_ms: 5000
    network_channel_size: 1024
    max_concurrent_network_reqs: 100
    discovery_method: onchain
    discovery_methods: []
    identity:
      type: from_file
      path: {vfn-identity-file}
    listen_address: /ip4/0.0.0.0/tcp/6181
    mutual_authentication: false
    network_id: public
    runtime_threads: ~
    seed_addrs: {}
    seeds: {}
    max_frame_size: 4194304
    enable_proxy_protocol: false
    ping_interval_ms: 10000
    ping_timeout_ms: 20000
    ping_failures_tolerated: 3
    max_outbound_connections: 0
    max_inbound_connections: 100
    inbound_rate_limit_config: ~
    outbound_rate_limit_config: ~
    max_message_size: 67108864
  - max_connection_delay_ms: 60000
    connection_backoff_base: 2
    connectivity_check_interval_ms: 5000
    network_channel_size: 1024
    max_concurrent_network_reqs: 100
    discovery_method: none
    discovery_methods: []
    identity:
      type: from_file
      path: {vfn-identity-file}
    listen_address: /ip4/0.0.0.0/tcp/63749
    mutual_authentication: false
    network_id:
      private: vfn
    runtime_threads: ~
    seed_addrs: {}
    seeds: {}
    max_frame_size: 4194304
    enable_proxy_protocol: false
    ping_interval_ms: 10000
    ping_timeout_ms: 20000
    ping_failures_tolerated: 3
    max_outbound_connections: 0
    max_inbound_connections: 100
    inbound_rate_limit_config: ~
    outbound_rate_limit_config: ~
    max_message_size: 67108864
inspection_service:
  address: 0.0.0.0
  port: 9101
  expose_configuration: false
  expose_system_information: true
logger:
  chan_size: 10000
  enable_backtrace: false
  is_async: true
  level: DEBUG
  console_port: ~
  enable_telemetry_remote_log: true
  enable_telemetry_flush: true
  telemetry_level: ERROR
mempool:
  capacity: 2000000
  capacity_bytes: 2147483648
  capacity_per_user: 100
  default_failovers: 3
  max_broadcasts_per_peer: 1
  mempool_snapshot_interval_secs: 180
  shared_mempool_ack_timeout_ms: 2000
  shared_mempool_backoff_interval_ms: 30000
  shared_mempool_batch_size: 100
  shared_mempool_max_batch_bytes: 64880640
  shared_mempool_max_concurrent_inbound_syncs: 4
  shared_mempool_tick_interval_ms: 50
  system_transaction_timeout_secs: 600
  system_transaction_gc_interval_ms: 60000
  shared_mempool_validator_broadcast: true
metrics: {}
peer_monitoring_service:
  max_concurrent_requests: 1000
  max_network_channel_size: 1000
api:
  enabled: true
  address: "0.0.0.0:8080"
  failpoints_enabled: false
  json_output_enabled: true
  bcs_output_enabled: true
  encode_submission_enabled: true
  transaction_submission_enabled: true
  transaction_simulation_enabled: true
  max_submit_transaction_batch_size: 100
state_sync:
  data_streaming_service:
    global_summary_refresh_interval_ms: 50
    max_concurrent_requests: 3
    max_concurrent_state_requests: 6
    max_data_stream_channel_sizes: 300
    max_request_retry: 3
    max_notification_id_mappings: 300
    progress_check_interval_ms: 100
  aptos_data_client:
    max_num_in_flight_priority_polls: 10
    max_num_in_flight_regular_polls: 10
    response_timeout_ms: 5000
    summary_poll_interval_ms: 200
    use_compression: true
  state_sync_driver:
    bootstrapping_mode: ApplyTransactionOutputsFromGenesis
    commit_notification_timeout_ms: 5000
    continuous_syncing_mode: ApplyTransactionOutputs
    progress_check_interval_ms: 100
    max_connection_deadline_secs: 10
    max_consecutive_stream_notifications: 10
    max_pending_data_chunks: 100
    max_stream_wait_time_ms: 5000
    num_versions_to_skip_snapshot_sync: 10000000
  storage_service:
    max_concurrent_requests: 4000
    max_epoch_chunk_size: 100
    max_lru_cache_size: 100
    max_network_channel_size: 4000
    max_network_chunk_bytes: 64880640
    max_state_chunk_size: 2000
    max_subscription_period_ms: 5000
    max_transaction_chunk_size: 2000
    max_transaction_output_chunk_size: 2000
    storage_summary_refresh_interval_ms: 50
firehose_stream:
  enabled: true
storage:
  address: "127.0.0.1:6666"
  backup_service_address: "127.0.0.1:6186"
  dir: db
  storage_pruner_config:
    ledger_pruner_config:
      enable: true
      prune_window: 150000000
      batch_size: 500
      user_pruning_window_offset: 200000
    state_merkle_pruner_config:
      enable: true
      prune_window: 100000
      batch_size: 1000
    epoch_snapshot_pruner_config:
      enable: true
      prune_window: 80000000
      batch_size: 1000
  target_snapshot_size: 100000
  max_num_nodes_per_lru_cache_shard: 8192
  rocksdb_configs:
    ledger_db_config:
      max_open_files: 5000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
    state_merkle_db_config:
      max_open_files: 5000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
    index_db_config:
      max_open_files: 1000
      max_total_wal_size: 1073741824
      max_background_jobs: 16
      block_cache_size: 8388608
      block_size: 4096
      cache_index_and_filter_blocks: false
  enable_indexer: true
test: ~
validator_network:
  max_connection_delay_ms: 60000
  connection_backoff_base: 2
  connectivity_check_interval_ms: 5000
  network_channel_size: 1024
  max_concurrent_network_reqs: 100
  discovery_method: onchain
  discovery_methods: []
  identity:
    type: from_file
    path: {validator-identity-file}
  listen_address: /ip4/0.0.0.0/tcp/6180
  mutual_authentication: true
  network_id: validator
  runtime_threads: ~
  seed_addrs: {}
  seeds: {}
  max_frame_size: 4194304
  enable_proxy_protocol: false
  ping_interval_ms: 10000
  ping_timeout_ms: 20000
  ping_failures_tolerated: 3
  max_outbound_connections: 4
  max_inbound_connections: 100
  inbound_rate_limit_config: ~
  outbound_rate_limit_config: ~
  max_message_size: 67108864
failpoints: ~
